spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tasks}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgresql}
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

